<a href="https://colab.research.google.com/github/mammu2007/myproject.ipynb/blob/main/numpy_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks=np.array([90,85,78,92])

print(marks)
print("Mean of marks:", np.mean(marks))

[90 85 78 92]


In [ ]:
import numpy as np

students = np.array([
    [90,85],
    [78,92],
    [88,95]
])
print(students)

[[90 85]
 [78 92]
 [88 95]]


In [ ]:
import numpy as np
arr = np.zeros((1,2))
print(arr)

[[0. 0.]]


In [ ]:
try:
  num=int(input("enter number:"))
  print(num)

except:
  print("invalid input")

enter number:23
23
